apiVersion: v1
kind: Pod 
metadata:
  name: pod-with-emptydir
spec:
  containers:
    - name: alpine
      image: alpine
      args:
        - /bin/sh
        - -c 
        - sleep 1d
      volumeMounts:
        - name: logs-volume 
          mountPath: /var/logs
        - name: data-volume 
          mountPath: /data
  volumes:
    - name: logs-volume
      emptyDir: {}
    - name: data-volume
      emptyDir: {}

