apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deploy
spec: 
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp-container
          image: mahesh91docker/myapp:1.0
          livenessProbe:
            httpGet:
              path: /
              port: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
          resources:
            requests:
              cpu: "500m"
              memory: "128Mi"
            limits: 
              cpu: "1000m"
              memory: "512Mi"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP