--- 
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-demo
spec:
  schedule: "*/30 * * * *"
  jobTemplate:
    metadata:
      labels:
        Cronjob: start-services
    spec:
      template:
        metadata:
          labels:
            Cronjob: start-services 
        spec:
          containers:
            - name: dummyjob
              image: alpine
              args:
                - /bin/sh
                - -c 
                - "sleep 2m" 
          restartPolicy: OnFailure
 
