--- 
apiVersion: batch/v1
kind: Job
metadata:
  name: job-demo
spec:
  template:
    metadata:
      labels: 
        job: start-services
    spec:
      containers:
        - name: dummyjob
          image: alpine
          args: 
            - /bin/bash
            - -c 
            - sleep2m 
    restartPolicy: OnFailure  