---
apiVersion: v1
kind: Pod
metadata:
  name: my-jenkins-pod
spec:
  containers:
    - name: jenkins
      image: jenkins/jenkins:jdk11
      ports:
        - name: jenkinsport
          containerPort: 8080
          protocol: TCP