apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: nginx-rs
spec:
  minReadySeconds: 5
  replicas: 2
  selector: 
    matchLabels: 
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        version: "1.21.1"
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.21.1
          livenessProbe:
            httpGet:
              path: /
              port: 80
          resources:
            requests: 
              memory: "128Mi"
              cpu: "500m"
            limits: 
              memory: "512Mi"
              cpu: "1000m"
          ports:
            - containerPort: 80
              name: http
              protocol: TCP