---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 80
      nodePort: 32000
      
