--- 
apiVersion: v1
kind: Pod 
metadata:
  name: ns-negative-demo
spec:
  containers:
    - name: alpine-cont
      image: alpine
      args:
        - /bin/sh
        - -c 
        - sleep 1d 
  nodeSelector:
    processor: intel