--- 
apiVersion: v1
kind: Pod 
metadata:
  name: secret-pod-demo 
spec:
  containers:
    - name: alpine-cont
      image: alpine
      args:
        - /bin/sh
        - -c 
        - sleep 1d
      volumeMounts:
        - name: secret-vol
          mountPath: "/secret"
          readOnly: true
  volumes:
    - name: secret-vol
      secret:
        secretName: my-secret 